In [63]:
import numpy as np
from random import randint

In [1]:
board =  [[5,3,0,0,7,0,0,0,0],
        [6,0,0,1,9,5,0,0,0],
        [0,9,8,0,0,0,0,6,0],
        [8,0,0,0,6,0,0,0,3],
        [4,0,0,8,0,3,0,0,1],
        [7,0,0,0,2,0,0,0,6],
        [0,6,0,0,0,0,2,8,0],
        [0,0,0,0,1,9,0,0,5],
        [0,0,0,0,0,0,0,0,0]]
board=[
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    ]
def random_numbers(board): 
    for i in range(len(board)):
        for j in range(len(board)):
            val=randint(0,1)
            if val==1:
                num=fill_position(i,j)
                board[i][j]=num
            else:
                board[i][j]=0
    return board

def fill_position(x,y):
    i=randint(1,9)
    while not is_valid(x,y,i):
        i= randint(1,9)
    return i


def print_board():
    global board
    for i in range(len(board)):
        if i%3==0:
            print("-------------------------")
        for j in range(len(board)):
            if j%3==0:
                print("|",end = " ")
            print(board[i][j],end=" ")
            if j==8:
                print("|",end="")
        print()
    print("-------------------------")
    
def is_valid(row,column,n):
    global board
    for i in range(len(board)):
        if board[i][column]==n:
            return False
    for j in range(len(board)):
        if board[row][j]==n:
            return False
    x_position=(row//3)*3
    y_position=(column//3)*3
    for i in range(3):
        for j in range(3):
            if board[x_position+i][y_position+j]==n:
                return False
    return True
def solve():
    global board
    for row in range(len(board)):
        for column in range(len(board)):
            if board[row][column]==0:
                for k in range(1,10):
                    if is_valid(row,column,k):
                        board[row][column]=k
                        solve()
                        board[row][column]=0
                return
    print_board()
    input("More")

solve()


-------------------------
| 1 2 3 | 4 5 6 | 7 8 9 |
| 4 5 6 | 7 8 9 | 1 2 3 |
| 7 8 9 | 1 2 3 | 4 5 6 |
-------------------------
| 2 1 4 | 3 6 5 | 8 9 7 |
| 3 6 5 | 8 9 7 | 2 1 4 |
| 8 9 7 | 2 1 4 | 3 6 5 |
-------------------------
| 5 3 1 | 6 4 2 | 9 7 8 |
| 6 4 2 | 9 7 8 | 5 3 1 |
| 9 7 8 | 5 3 1 | 6 4 2 |
-------------------------


-------------------------
| 1 2 3 | 4 5 6 | 7 8 9 |
| 4 5 6 | 7 8 9 | 1 2 3 |
| 7 8 9 | 1 2 3 | 4 5 6 |
-------------------------
| 2 1 4 | 3 6 5 | 8 9 7 |
| 3 6 5 | 8 9 7 | 2 1 4 |
| 8 9 7 | 2 1 4 | 3 6 5 |
-------------------------
| 5 3 1 | 6 4 2 | 9 7 8 |
| 6 4 8 | 9 7 1 | 5 3 2 |
| 9 7 2 | 5 3 8 | 6 4 1 |
-------------------------
-------------------------
| 1 2 3 | 4 5 6 | 7 8 9 |
| 4 5 6 | 7 8 9 | 1 2 3 |
| 7 8 9 | 1 2 3 | 4 5 6 |
-------------------------
| 2 1 4 | 3 6 5 | 8 9 7 |
| 3 6 5 | 8 9 7 | 2 1 4 |
| 8 9 7 | 2 1 4 | 3 6 5 |
-------------------------
| 5 3 1 | 6 4 2 | 9 7 8 |
| 6 7 2 | 9 3 8 | 5 4 1 |
| 9 4 8 | 5 7 1 | 6 3 2 |
-------------------------
-------------------------
| 1 2 3 | 4 5 6 | 7 8 9 |
| 4 5 6 | 7 8 9 | 1 2 3 |
| 7 8 9 | 1 2 3 | 4 5 6 |
-------------------------
| 2 1 4 | 3 6 5 | 8 9 7 |
| 3 6 5 | 8 9 7 | 2 1 4 |
| 8 9 7 | 2 1 4 | 3 6 5 |
-------------------------
| 5 3 1 | 6 4 2 | 9 7 8 |
| 6 7 8 | 9 3 1 | 5 4 2 |
| 9 4 2 | 5 7 8 | 6 3 1 |
------------

In [65]:
def print_board():
    global board
    for i in range(len(board)):
        if i%3==0:
            print("-------------------------")
        for j in range(len(board)):
            if j%3==0:
                print("|",end = " ")
            print(board[i][j],end=" ")
            if j==8:
                print("|",end="")
        print()
    print("-------------------------")

In [66]:
def is_valid(row,column,n):
    global board
    for i in range(len(board)):
        if board[i][column]==n:
            return False
    for j in range(len(board)):
        if board[row][j]==n:
            return False
    x_position=(row//3)*3
    y_position=(column//3)*3
    for i in range(3):
        for j in range(3):
            if board[x_position+i][y_position+j]==n:
                return False
    return True

In [67]:
def solve():
    global board
    for row in range(len(board)):
        for column in range(len(board)):
            if board[row][column]==0:
                for k in range(1,10):
                    if is_valid(row,column,k):
                        board[row][column]=k
                        solve()
                        board[row][column]=0
                return

In [68]:
solve()

In [69]:
board

[[5, 3, 0, 0, 7, 0, 0, 0, 0],
 [6, 0, 0, 1, 9, 5, 0, 0, 0],
 [0, 9, 8, 0, 0, 0, 0, 6, 0],
 [8, 0, 0, 0, 6, 0, 0, 0, 3],
 [4, 0, 0, 8, 0, 3, 0, 0, 1],
 [7, 0, 0, 0, 2, 0, 0, 0, 6],
 [0, 6, 0, 0, 0, 0, 2, 8, 0],
 [0, 0, 0, 0, 1, 9, 0, 0, 5],
 [0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [70]:
print(np.matrix(board))

[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 0 1 9 0 0 5]
 [0 0 0 0 0 0 0 0 0]]


In [61]:
print_board()

-------------------------
| 5 3 0 | 0 7 0 | 0 0 0 |
| 6 0 0 | 1 9 5 | 0 0 0 |
| 0 9 8 | 0 0 0 | 0 6 0 |
-------------------------
| 8 0 0 | 0 6 0 | 0 0 3 |
| 4 0 0 | 8 0 3 | 0 0 1 |
| 7 0 0 | 0 2 0 | 0 0 6 |
-------------------------
| 0 6 0 | 0 0 0 | 2 8 0 |
| 0 0 0 | 0 1 9 | 0 0 5 |
| 0 0 0 | 0 0 0 | 0 0 0 |
-------------------------


In [62]:
import numpy as np

grid = [[5,3,0,0,7,0,0,0,0],
        [6,0,0,1,9,5,0,0,0],
        [0,9,8,0,0,0,0,6,0],
        [8,0,0,0,6,0,0,0,3],
        [4,0,0,8,0,3,0,0,1],
        [7,0,0,0,2,0,0,0,6],
        [0,6,0,0,0,0,2,8,0],
        [0,0,0,0,1,9,0,0,5],
        [0,0,0,0,0,0,0,0,0]]

def possible(row, column, number):
    global grid
    #Is the number appearing in the given row?
    for i in range(0,9):
        if grid[row][i] == number:
            return False

    #Is the number appearing in the given column?
    for i in range(0,9):
        if grid[i][column] == number:
            return False
    
    #Is the number appearing in the given square?
    x0 = (column // 3) * 3
    y0 = (row // 3) * 3
    for i in range(0,3):
        for j in range(0,3):
            if grid[y0+i][x0+j] == number:
                return False

    return True

def solve():
    global grid
    for row in range(0,9):
        for column in range(0,9):
            if grid[row][column] == 0:
                for number in range(1,10):
                    if possible(row, column, number):
                        grid[row][column] = number
                        solve()
                        grid[row][column] = 0

                return
      
    print(np.matrix(grid))
    # input('More possible solutions')

solve()



[[5 3 4 6 7 8 1 9 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 9 7 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 7 1 9]]
[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
